### ISSUE TITLE
`sendError` sets `isAd = true`, `isAd = this.isAd()` sounds more accurate

### ISSUE THREAD

**Issue by timalacey** [newrelic/video-core-js#5]
Current
```
att.isAd = true
```
https://github.com/newrelic/video-core-js/blob/173c69ae18502f23cc00426a8f218f8f43596b4f/src/videotracker.js#L712

Suggestion
```
att.isAd = this.isAd()
```

**Comment by asllop** [comment]
Good catch. Thanks for reporting.

**Comment by timalacey** [comment]
Thanks for fixing :)
